/* MorphoDeutsch — Workbook data: Wortbildung der Adjektive (suffixes and prefixes).
   WB_ELEMS: the rule behind every building element the workbook uses (meaning, signal, joint, warning).
   WB_SETS:  the exercise sheets (Aufgaben). The adjectives come from the Wortbildung chapters of the course
             grammars (B2 and C1 level); every phrase and sentence around them is written fresh.
   Item kinds:
     N  base word → adjective before a noun, nominative   (der Regen → regnerisches Wetter)
     T  cue sentence → adjective in a sentence gap        (… kann man essen. → … sind essbar.)
     O  adjective → its opposite before the same noun     (die direkte Rede ↔ die indirekte Rede)
   Noun spec: "der Tag", "die Lösung", "das Wetter", or "pl Kosten" for a plural.
   art: indef (ein/eine) | def (der/die/das) | zero (no article).
   alts:  other adjectives that are also right in this phrase (lemmas).
   note:  what happens at the joint in this word.   tip: any other remark.
   traps: real words built on the same base that mean something else, with what they mean
          (a text starting with ~ is a remark about a form that is not a standard word of its own).
   Checked by tests/workbook-test.mjs (forms, spelling, one gap, a rule for every item). */

const WB_ELEMS = {
  ig: {form:'-ig', kind:'suffix', mean:'having or showing it: sonnig = with sun. With a time span: lasting that long.',
    sig:'German nouns, mostly short ones: Sonne, Wind, Mut, Geduld, Ruhe.',
    joint:'A final -e drops (Sonne → sonnig). a, o, u often take an umlaut (Vernunft → vernünftig). -el and -er lose their e (Nebel → neblig).',
    warn:'With time words, -ig is duration and -lich is repetition: dreitägig = lasting three days, täglich = every day.'},
  lich: {form:'-lich', kind:'suffix', mean:'relating to, in the manner of. With a time word: every … On a verb stem: it can or must be done.',
    sig:'German nouns and verb stems: Freund, Beruf, Tag, bedauern.',
    joint:'Very often with an umlaut (Tag → täglich, Punkt → pünktlich). A few words insert a sound: wöchentlich, morgendlich.',
    warn:'The same base can take -lich and another suffix with a different meaning: kindlich (like a child) and kindisch (childish), geistlich (of the church) and geistig (of the mind).'},
  isch: {form:'-isch', kind:'suffix', mean:'belonging to, typical of.',
    sig:'Countries, peoples and places (französisch, städtisch), nouns in -ist, -ie, -ik and -iker (optimistisch, sympathisch, kosmetisch, cholerisch), and character words, often with a critical tone (launisch, neidisch, kindisch).',
    joint:'The endings -e, -ie, -ik, -iker and -en drop. a, o, u often take an umlaut (Sturm → stürmisch). A few words insert -er-, -n- or -or- (regnerisch, amerikanisch, organisatorisch).'},
  bar: {form:'-bar', kind:'suffix', mean:'it can be done: essbar = can be eaten.',
    sig:'The stem of a verb that takes an object: essen → essbar, lösen → lösbar. A few old words come from nouns: furchtbar, kostbar, wunderbar.',
    joint:'Take the verb, remove -en, add -bar. No umlaut.',
    warn:'un- in front gives the opposite: unheilbar, unbezahlbar.'},
  abel: {form:'-abel', kind:'suffix', mean:'it can be done (the foreign twin of -bar).',
    sig:'Foreign verbs in -ieren: akzeptieren → akzeptabel, variieren → variabel.',
    joint:'Remove -ieren, add -abel. Before an ending the e drops: variabel → variable Kosten, eine akzeptable Lösung.',
    warn:'Often a form in -ierbar exists as well: akzeptierbar, reparierbar.'},
  'fähig': {form:'-fähig', kind:'suffix', mean:'able to do it, or fit for it.',
    sig:'Nouns and verb stems: arbeitsfähig, lernfähig, ausbaufähig.',
    joint:'Linking -s after -ung, -heit, -keit, -schaft, -ion, -tät and after Arbeit: anpassungsfähig, arbeitsfähig.',
    warn:'-bar is about the thing (Das ist lernbar = it can be learned). -fähig is usually about the one who does it (Sie ist lernfähig = she is able to learn).'},
  sam: {form:'-sam', kind:'suffix', mean:'tending to, inclined to: sparsam = inclined to save.',
    sig:'Verb stems (sparen, schweigen, wirken) and a few nouns (Mühe, Arbeit, Gewalt).',
    joint:'Remove -en from the verb or -e from the noun: Mühe → mühsam.',
    warn:'Not the same as -bar: heilsam = doing you good, heilbar = curable.'},
  haft: {form:'-haft', kind:'suffix', mean:'having the character of, like.',
    sig:'Nouns: Schmerz, Vorteil, Rätsel, Märchen.',
    joint:'Usually added straight to the noun. Name loses its -e (namhaft). Frühling takes a linking -s (frühlingshaft).',
    warn:'-haft is often literal where -lich is figurative: schmerzhaft (it hurts the body), schmerzlich (it hurts the feelings).'},
  'mäßig': {form:'-mäßig', kind:'suffix', mean:'according to, in the manner of.',
    sig:'Nouns: Regel, Plan, Recht, Routine.',
    joint:'Added straight to the noun; linking -s after -ung, -heit, -keit, -schaft. Maß itself turns into -mäßig: Mittelmaß → mittelmäßig.'},
  'gemäß': {form:'-gemäß', kind:'suffix', mean:'in accordance with, as it requires.',
    sig:'Nouns, mostly from official language: Vertrag, Frist, Ordnung, Zeit.',
    joint:'Linking -s after -ung and -heit and after Vertrag: ordnungsgemäß, wahrheitsgemäß, vertragsgemäß.',
    warn:'Close to -mäßig; -gemäß stresses that a requirement is met.'},
  al: {form:'-al / -ial', kind:'suffix', mean:'relating to.',
    sig:'Latin nouns, often in -ion, -um or -e: Region, Nation, Zentrum, Kollege.',
    joint:'Endings like -um and -e drop: Zentrum → zentral, Kollege → kollegial.',
    warn:'Some bases take both -al and -ell with different meanings: rational (guided by reason) and rationell (efficient), formal (about the form) and formell (by etiquette).'},
  ell: {form:'-ell / -iell', kind:'suffix', mean:'relating to.',
    sig:'Latin and French nouns, often in -ur, -ion or -ie: Kultur, Tradition, Industrie. After -enz and -anz the form is -iell: Potenz → potenziell, Finanzen → finanziell.',
    joint:'A final -e drops: Industrie → industriell.',
    warn:'Some bases take both -al and -ell with different meanings: rational (guided by reason) and rationell (efficient), formal (about the form) and formell (by etiquette).'},
  iv: {form:'-iv', kind:'suffix', mean:'having that quality or effect.',
    sig:'Nouns in -ion pair with adjectives in -iv: Information → informativ, Produktion → produktiv. Also Impuls → impulsiv.',
    joint:'Remove -ion, add -iv.'},
  'ös': {form:'-ös / -iös', kind:'suffix', mean:'full of, marked by (from French -eux).',
    sig:'A small group of foreign nouns: Nerv, Skandal, Religion, Luxus.',
    joint:'Often -iös on a shortened base: Religion → religiös, Luxus → luxuriös.'},
  los: {form:'-los', kind:'suffix', mean:'without (English -less). The opposite of -voll and -reich.',
    sig:'Nouns: Schlaf, Arbeit, Erfolg, Hoffnung.',
    joint:'Linking -s after -ung, -heit, -keit, -schaft and after Arbeit, Rücksicht, Einfall. Some nouns take -n or -er (grenzenlos, kinderlos). A final -e can drop (Ende → endlos, Sprache → sprachlos).',
    warn:'Irregular pairs: liebevoll ↔ lieblos, sorgenvoll ↔ sorglos.'},
  voll: {form:'-voll', kind:'suffix', mean:'full of, with a lot of.',
    sig:'Nouns: Sinn, Wert, Respekt, Hoffnung.',
    joint:'Linking -s after -ung and -sicht and after Anspruch: hoffnungsvoll, rücksichtsvoll, anspruchsvoll.',
    warn:'The opposite is usually -los: sinnvoll ↔ sinnlos.'},
  wert: {form:'-wert', kind:'suffix', mean:'worth it.',
    sig:'Nouns (preiswert) and, with a linking -s, whole infinitives (sehenswert, lesenswert).',
    joint:'Nouns join directly: Preis → preiswert. Verbs keep the infinitive and take -s: sehen·s·wert.'},
  un: {form:'un-', kind:'prefix', mean:'not.',
    sig:'German adjectives and all participles (unfreundlich, unbefristet, ungeeignet), and many everyday foreign words (unsympathisch, unpopulär, uninteressant).',
    joint:'Simply put in front. The stress moves to un-.',
    warn:'Many Latin adjectives take in- instead: indirekt, inkompetent.'},
  in: {form:'in- / im- / il- / ir-', kind:'prefix', mean:'not.',
    sig:'Latin and French adjectives: indirekt, inkompetent, informell, intolerant.',
    joint:'in- adapts to the next sound: im- before m, p and b (immobil), il- before l (illegal), ir- before r (irrational).',
    warn:'Never on German words: unhöflich, not "inhöflich".'},
  miss: {form:'miss-', kind:'prefix', mean:'wrongly, badly: it went wrong.',
    sig:'German verbs and their participles: missverstehen, misslingen, missachten.',
    joint:'On a participle, miss- takes the place of ge- or be-: gelungen ↔ misslungen, beachtet ↔ missachtet.',
    warn:'missverständlich = easy to misunderstand; unverständlich = impossible to understand.'},
  de: {form:'de- / des-', kind:'prefix', mean:'undone, taken away again.',
    sig:'Latin verbs in -ieren and their participles: deaktiviert, demontiert, deinstalliert.',
    joint:'de- is the normal form. A few words that came through French use des- before a vowel: desinteressiert, desorganisiert, desinfiziert, desorientiert.',
    warn:'de- reverses an action; un- only says "not": demotiviert = the motivation was lost, unmotiviert = there is none.'},
  non: {form:'non-', kind:'prefix', mean:'not (only in a few fixed terms).',
    sig:'A handful of Latin and English terms: nonverbal, nonkonform, nonstop.',
    joint:'Written as one word.',
    warn:'Not a living prefix: you cannot put non- on any adjective you like.'},
  intens: {form:'noun + adjective', kind:'first', mean:'very, extremely. The first word is a comparison: steinreich, federleicht.',
    sig:'Fixed combinations that have to be learned: German says blitzschnell, never "steinschnell".',
    joint:'The two words are simply joined.',
    warn:'Vivid and colloquial. In formal writing use sehr, äußerst or extrem.'}
};

const WB_SETS = (() => {
  const P = s => s.split('|');
  const N = (from, w, parts, el, noun, art, en, x) => Object.assign({k:'N', from, w, parts:P(parts), el, noun, art, en}, x || {});
  const T = (from, w, parts, el, cue, s, en, x) => Object.assign({k:'T', from, w, parts:P(parts), el, cue, s, a:w, en}, x || {});
  const O = (pos, w, parts, el, noun, art, en, x) => Object.assign({k:'O', pos, w, parts:P(parts), el, noun, art, en}, x || {});
  // time words: -ig = how long, -lich = how often. The twin with the other suffix is the standing trap.
  const DUR = '~-lich says how often something happens (every …). This phrase says how long it lasts.';
  const REP = '~-ig says how long something lasts. This phrase says how often it happens.';
  const Z = (from, w, parts, el, noun, art, en, x) => {
    const it = N(from, w, parts, el, noun, art, en, x);
    const twin = it.twin || (el === 'ig' ? w.replace(/ig$/, 'lich') : w.replace(/lich$/, 'ig'));
    delete it.twin;
    it.traps = Object.assign({[twin]: (el === 'ig' ? DUR : REP)}, it.traps || {});
    return it;
  };

  return [
  /* ============================ SUFFIXES ============================ */
  { id:'mix', group:'suffix', level:'C1', title:'One word, one suffix',
    task:'Build an adjective from each word with one of these suffixes and write it with the right ending.',
    els:['sam','mäßig','ig','isch','haft','iv','ell','bar','abel','al','lich'],
    example:N('die Sonne', 'sonnig', 'sonn|ig', 'ig', 'der Nachmittag', 'indef', 'sunny'),
    items:[
      N('der Regen', 'regnerisch', 'regn|er|isch', 'isch', 'das Wetter', 'zero', 'rainy',
        {note:'Regen loses its e and takes -er- before -isch: regn·er·isch.', traps:{regenreich:'regenreich means with a lot of rain over a longer time: ein regenreicher Sommer.'}}),
      N('der Zeitgenosse', 'zeitgenössisch', 'zeitgenöss|isch', 'isch', 'die Musik', 'zero', 'contemporary', {note:'o → ö, and the final -e drops.'}),
      N('die Vernunft', 'vernünftig', 'vernünft|ig', 'ig', 'die Lösung', 'indef', 'sensible, reasonable',
        {note:'u → ü.', traps:{'vernunftmäßig':'vernunftmäßig is a rare, bookish word (in line with reason). The everyday word for sensible takes another ending.'}}),
      N('die Dauer', 'dauerhaft', 'dauer|haft', 'haft', 'der Frieden', 'indef', 'lasting, permanent'),
      N('sparen', 'sparsam', 'spar|sam', 'sam', 'die Familie', 'indef', 'thrifty, economical',
        {traps:{'spärlich':'spärlich means sparse, scanty: spärliches Licht.'}}),
      N('das Gesetz', 'gesetzlich', 'gesetz|lich', 'lich', 'der Feiertag', 'indef', 'legal, fixed by law',
        {traps:{'gesetzmäßig':'gesetzmäßig means following a law of nature or a fixed pattern: eine gesetzmäßige Entwicklung.'}}),
      N('der Impuls', 'impulsiv', 'impuls|iv', 'iv', 'die Reaktion', 'indef', 'impulsive'),
      N('die Form', 'formell', 'form|ell', 'ell', 'die Einladung', 'indef', 'formal, following etiquette',
        {alts:['förmlich'], traps:{formal:'formal is about the outer form only: ein formaler Fehler.', formbar:'formbar means easy to shape: formbares Material.'}}),
      N('die Region', 'regional', 'region|al', 'al', 'pl Zeitungen', 'zero', 'regional'),
      N('bedauern', 'bedauerlich', 'bedauer|lich', 'lich', 'der Irrtum', 'indef', 'regrettable',
        {note:'Verb stem + -lich: something one has to regret.', traps:{bedauernswert:'bedauernswert means deserving pity: ein bedauernswerter Mensch.'}}),
      N('das Mittelmaß', 'mittelmäßig', 'mittel|mäßig', 'mäßig', 'der Film', 'indef', 'mediocre', {note:'Maß itself turns into -mäßig: Mittelmaß → mittelmäßig.'}),
      N('die Furcht', 'furchtbar', 'furcht|bar', 'bar', 'der Sturm', 'indef', 'terrible, dreadful',
        {alts:['fürchterlich'], traps:{furchtsam:'furchtsam means timid, easily frightened: ein furchtsames Kind.', furchtlos:'furchtlos means fearless: ein furchtloser Retter.'}}),
      N('der Monat', 'monatlich', 'monat|lich', 'lich', 'die Miete', 'def', 'monthly',
        {note:'No umlaut.', traps:{monatig:'~-monatig only works with a number in front, and then it means lasting that long: dreimonatig.'}}),
      N('abwaschen', 'abwaschbar', 'abwasch|bar', 'bar', 'die Farbe', 'zero', 'washable'),
      N('variieren', 'variabel', 'vari|abel', 'abel', 'pl Kosten', 'zero', 'variable', {alts:['variierbar'], tip:'Before an ending the e of -abel drops: variabel → variable.'})
    ]},

  { id:'wetter', group:'suffix', level:'B2', title:'Weather and seasons',
    task:'-ig, -lich, -isch or -haft? Watch for umlauts and for an e that drops.',
    els:['ig','lich','isch','haft'],
    example:N('die Wolke', 'wolkig', 'wolk|ig', 'ig', 'der Himmel', 'indef', 'cloudy'),
    items:[
      N('der Wind', 'windig', 'wind|ig', 'ig', 'der Tag', 'indef', 'windy'),
      N('der Nebel', 'neblig', 'nebl|ig', 'ig', 'der Morgen', 'indef', 'foggy', {alts:['nebelig'], note:'The e of Nebel drops: nebl·ig (nebelig is also correct).'}),
      N('der Winter', 'winterlich', 'winter|lich', 'lich', 'pl Temperaturen', 'zero', 'wintry'),
      N('der Sommer', 'sommerlich', 'sommer|lich', 'lich', 'der Abend', 'indef', 'summery'),
      N('der Herbst', 'herbstlich', 'herbst|lich', 'lich', 'pl Farben', 'zero', 'autumnal'),
      N('der Sturm', 'stürmisch', 'stürm|isch', 'isch', 'die Nacht', 'indef', 'stormy', {note:'u → ü.'}),
      N('das Eis', 'eisig', 'eis|ig', 'ig', 'der Wind', 'indef', 'icy'),
      N('der Frost', 'frostig', 'frost|ig', 'ig', 'pl Nächte', 'zero', 'frosty'),
      N('das Gewitter', 'gewittrig', 'gewittr|ig', 'ig', 'das Wetter', 'zero', 'thundery', {alts:['gewitterig'], note:'The e of Gewitter drops: gewittr·ig.'}),
      N('der Frühling', 'frühlingshaft', 'frühling|s|haft', 'haft', 'der Nachmittag', 'indef', 'springlike', {note:'Linking -s after -ling.'}),
      N('die Nacht', 'nächtlich', 'nächt|lich', 'lich', 'die Stille', 'zero', 'nightly, of the night', {note:'a → ä.'}),
      N('der Morgen', 'morgendlich', 'morgen|d|lich', 'lich', 'der Nebel', 'zero', 'morning (adj.)',
        {note:'A -d- is inserted: morgen·d·lich.', traps:{morgig:'morgig means of tomorrow: der morgige Tag.'}})
    ]},

  { id:'mensch', group:'suffix', level:'B2', title:'People and character',
    task:'-ig, -lich or -isch? Nouns in -ist, -ie and -iker take -isch.',
    els:['ig','lich','isch'],
    example:N('die Geduld', 'geduldig', 'geduld|ig', 'ig', 'der Lehrer', 'indef', 'patient'),
    items:[
      N('der Mut', 'mutig', 'mut|ig', 'ig', 'die Entscheidung', 'indef', 'brave, courageous'),
      N('der Witz', 'witzig', 'witz|ig', 'ig', 'die Bemerkung', 'indef', 'witty, funny'),
      N('die Ruhe', 'ruhig', 'ruh|ig', 'ig', 'der Kollege', 'indef', 'calm, quiet', {note:'The final -e drops.'}),
      N('die Selbstsucht', 'selbstsüchtig', 'selbstsücht|ig', 'ig', 'das Verhalten', 'zero', 'selfish', {note:'u → ü.'}),
      N('die Risikofreude', 'risikofreudig', 'risikofreud|ig', 'ig', 'pl Anleger', 'zero', 'willing to take risks', {note:'The final -e drops.'}),
      N('die Neugier', 'neugierig', 'neugier|ig', 'ig', 'die Frage', 'indef', 'curious'),
      N('der Freund', 'freundlich', 'freund|lich', 'lich', 'die Verkäuferin', 'indef', 'friendly'),
      N('die Leidenschaft', 'leidenschaftlich', 'leidenschaft|lich', 'lich', 'der Koch', 'indef', 'passionate'),
      N('der Punkt', 'pünktlich', 'pünkt|lich', 'lich', 'der Gast', 'indef', 'punctual', {note:'u → ü.'}),
      N('die Angst', 'ängstlich', 'ängst|lich', 'lich', 'das Kind', 'indef', 'anxious, timid', {note:'a → ä.'}),
      N('die Ehre', 'ehrlich', 'ehr|lich', 'lich', 'die Antwort', 'indef', 'honest', {note:'The final -e drops.'}),
      N('die Sympathie', 'sympathisch', 'sympath|isch', 'isch', 'der Nachbar', 'indef', 'likeable', {note:'The ending -ie drops before -isch.'}),
      N('der Optimist', 'optimistisch', 'optimist|isch', 'isch', 'die Prognose', 'indef', 'optimistic'),
      N('die Laune', 'launisch', 'laun|isch', 'isch', 'der Chef', 'indef', 'moody',
        {note:'The final -e drops. No umlaut.', traps:{launig:'launig means witty, good-humoured: eine launige Rede.'}}),
      N('der Neid', 'neidisch', 'neid|isch', 'isch', 'der Blick', 'indef', 'envious',
        {traps:{neidig:'~neidig is regional (southern Germany, Austria). The standard word takes another ending.'}}),
      N('das Misstrauen', 'misstrauisch', 'misstrau|isch', 'isch', 'die Nachbarin', 'indef', 'suspicious, distrustful', {note:'The noun ending -en drops.'}),
      N('der Angeber', 'angeberisch', 'angeber|isch', 'isch', 'der Typ', 'indef', 'boastful, showy'),
      N('der Choleriker', 'cholerisch', 'choler|isch', 'isch', 'der Trainer', 'indef', 'hot-tempered', {note:'-iker drops: Choleriker → choler·isch.'})
    ]},

  { id:'zeit', group:'suffix', level:'B2', title:'Time: how long or how often?',
    task:'-ig says how long something lasts, -lich says how often it happens. Build the adjective from the time phrase.',
    els:['ig','lich'],
    example:N('drei Tage lang', 'dreitägig', 'drei|täg|ig', 'ig', 'die Konferenz', 'indef', 'three-day, lasting three days'),
    items:[
      Z('jede Woche', 'wöchentlich', 'wöch|ent|lich', 'lich', 'die Besprechung', 'def', 'weekly', {twin:'wöchig', note:'o → ö, and -ent- is inserted: wöch·ent·lich.'}),
      Z('jeden Tag', 'täglich', 'täg|lich', 'lich', 'das Training', 'def', 'daily', {note:'a → ä.'}),
      Z('jedes Jahr', 'jährlich', 'jähr|lich', 'lich', 'die Steuererklärung', 'def', 'annual, yearly', {note:'a → ä.'}),
      Z('jede Stunde', 'stündlich', 'stünd|lich', 'lich', 'pl Nachrichten', 'def', 'hourly', {note:'u → ü, and the final -e drops.'}),
      Z('jedes Vierteljahr', 'vierteljährlich', 'viertel|jähr|lich', 'lich', 'die Abrechnung', 'def', 'quarterly'),
      Z('jedes halbe Jahr', 'halbjährlich', 'halb|jähr|lich', 'lich', 'die Kontrolle', 'indef', 'half-yearly, every six months'),
      Z('alle vierzehn Tage', 'vierzehntäglich', 'vierzehn|täg|lich', 'lich', 'das Treffen', 'indef', 'fortnightly, every two weeks', {alts:['zweiwöchentlich']}),
      Z('zwei Wochen lang', 'zweiwöchig', 'zwei|wöch|ig', 'ig', 'der Kurs', 'indef', 'two-week, lasting two weeks', {twin:'zweiwöchentlich', note:'o → ö.'}),
      Z('drei Jahre lang', 'dreijährig', 'drei|jähr|ig', 'ig', 'das Studium', 'def', 'three-year, lasting three years'),
      Z('vier Monate lang', 'viermonatig', 'vier|monat|ig', 'ig', 'das Praktikum', 'indef', 'four-month, lasting four months', {note:'No umlaut: monatig, monatlich.'}),
      Z('zwei Stunden lang', 'zweistündig', 'zwei|stünd|ig', 'ig', 'die Sitzung', 'indef', 'two-hour, lasting two hours'),
      Z('den ganzen Tag lang', 'ganztägig', 'ganz|täg|ig', 'ig', 'die Schulung', 'indef', 'all-day'),
      Z('ein halbes Jahr lang', 'halbjährig', 'halb|jähr|ig', 'ig', 'der Auslandsaufenthalt', 'indef', 'lasting six months'),
      Z('vierzehn Tage lang', 'vierzehntägig', 'vierzehn|täg|ig', 'ig', 'die Reise', 'indef', 'two-week, lasting fourteen days', {alts:['zweiwöchig']}),
      Z('mehrere Tage lang', 'mehrtägig', 'mehr|täg|ig', 'ig', 'die Wanderung', 'indef', 'lasting several days')
    ]},

  { id:'bar', group:'suffix', level:'B2', title:'Can it be done?',
    task:'Say the same thing with an adjective in -bar, -abel or -fähig. After sein the adjective takes no ending.',
    els:['bar','abel','fähig'],
    example:T('trinken', 'trinkbar', 'trink|bar', 'bar', 'Dieses Wasser kann man trinken.', 'Dieses Wasser ist ___.', 'drinkable'),
    items:[
      T('essen', 'essbar', 'ess|bar', 'bar', 'Diese Pilze kann man essen.', 'Diese Pilze sind ___.', 'edible'),
      T('heilen', 'heilbar', 'heil|bar', 'bar', 'Diese Infektion kann man heilen.', 'Diese Infektion ist ___.', 'curable',
        {traps:{heilsam:'heilsam means doing you good: eine heilsame Erfahrung.'}}),
      T('verschieben', 'verschiebbar', 'verschieb|bar', 'bar', 'Den Termin kann man verschieben.', 'Der Termin ist ___.', 'movable, can be postponed'),
      T('bezahlen', 'bezahlbar', 'bezahl|bar', 'bar', 'Diese Wohnung können wir bezahlen.', 'Diese Wohnung ist ___.', 'affordable'),
      T('verändern', 'veränderbar', 'veränder|bar', 'bar', 'Die Einstellungen kann man verändern.', 'Die Einstellungen sind ___.', 'changeable, can be modified',
        {alts:['änderbar'], traps:{'veränderlich':'veränderlich means changing by itself, unstable: veränderliches Wetter.'}}),
      T('abrufen', 'abrufbar', 'abruf|bar', 'bar', 'Die Ergebnisse kann man online abrufen.', 'Die Ergebnisse sind online ___.', 'retrievable, available'),
      T('vermeiden', 'vermeidbar', 'vermeid|bar', 'bar', 'Diesen Fehler hätte man vermeiden können.', 'Dieser Fehler war ___.', 'avoidable'),
      T('hören', 'hörbar', 'hör|bar', 'bar', 'Den Unterschied kann man kaum hören.', 'Der Unterschied ist kaum ___.', 'audible'),
      T('akzeptieren', 'akzeptabel', 'akzept|abel', 'abel', 'Diesen Preis können wir akzeptieren.', 'Dieser Preis ist ___.', 'acceptable', {alts:['akzeptierbar']}),
      T('diskutieren', 'diskutabel', 'diskut|abel', 'abel', 'Über diesen Vorschlag kann man diskutieren.', 'Dieser Vorschlag ist ___.', 'worth discussing', {alts:['diskutierbar']}),
      T('reparieren', 'reparabel', 'repar|abel', 'abel', 'Den Schaden kann man reparieren.', 'Der Schaden ist ___.', 'repairable', {alts:['reparierbar']}),
      T('die Arbeit', 'arbeitsfähig', 'arbeit|s|fähig', 'fähig', 'Nach der Operation kann er wieder arbeiten.', 'Er ist wieder ___.', 'fit for work', {note:'Linking -s after Arbeit.'}),
      T('lernen', 'lernfähig', 'lern|fähig', 'fähig', 'Kleine Kinder können sehr gut lernen.', 'Kleine Kinder sind sehr ___.', 'able to learn',
        {traps:{lernbar:'lernbar is said of the thing that is learned: Die Sprache ist lernbar.'}}),
      T('der Ausbau', 'ausbaufähig', 'ausbau|fähig', 'fähig', 'Sein Französisch kann er noch ausbauen.', 'Sein Französisch ist noch ___.', 'capable of improvement', {alts:['ausbaubar']}),
      T('die Konkurrenz', 'konkurrenzfähig', 'konkurrenz|fähig', 'fähig', 'Die Firma kann mit der Konkurrenz mithalten.', 'Die Firma ist ___.', 'competitive'),
      T('die Anpassung', 'anpassungsfähig', 'anpassung|s|fähig', 'fähig', 'Sie kann sich schnell an Neues anpassen.', 'Sie ist sehr ___.', 'adaptable',
        {note:'Linking -s after -ung.', traps:{anpassbar:'anpassbar is said of a thing that can be adjusted: ein anpassbares Profil.'}})
    ]},

  { id:'fremd', group:'suffix', level:'B2', title:'Latin and French endings',
    task:'-al, -ell, -iv or -ös? Nouns in -ion often pair with -iv or -ell; after -enz and -anz the ending is -iell.',
    els:['al','ell','iv','ös'],
    example:N('die Nation', 'national', 'nation|al', 'al', 'pl Interessen', 'zero', 'national'),
    items:[
      N('die Kultur', 'kulturell', 'kultur|ell', 'ell', 'pl Unterschiede', 'zero', 'cultural'),
      N('der Kollege', 'kollegial', 'kolleg|ial', 'al', 'die Hilfe', 'zero', 'helpful as a colleague', {note:'The final -e drops and the ending is -ial: kolleg·ial.'}),
      N('die Produktion', 'produktiv', 'produkt|iv', 'iv', 'das Gespräch', 'indef', 'productive', {note:'-ion goes, -iv comes: Produktion → produkt·iv.'}),
      N('die Information', 'informativ', 'informat|iv', 'iv', 'der Vortrag', 'indef', 'informative',
        {note:'-ion goes, -iv comes.', traps:{informationell:'informationell is a legal term: informationelle Selbstbestimmung.'}}),
      N('der Nerv', 'nervös', 'nerv|ös', 'ös', 'der Kandidat', 'indef', 'nervous',
        {traps:{nervig:'nervig means annoying: ein nerviges Geräusch.', nervlich:'nervlich means concerning the nerves: nervliche Belastung.'}}),
      N('die Religion', 'religiös', 'relig|iös', 'ös', 'das Fest', 'indef', 'religious', {note:'-ion goes and the ending is -iös: relig·iös.'}),
      N('die Potenz', 'potenziell', 'potenz|iell', 'ell', 'pl Kunden', 'zero', 'potential', {alts:['potentiell'], note:'After -enz the ending is -iell (also spelled potentiell).', traps:{potent:'potent means powerful, financially strong: ein potenter Investor.'}}),
      N('die Finanzen', 'finanziell', 'finanz|iell', 'ell', 'die Unterstützung', 'zero', 'financial', {note:'After -anz the ending is -iell.'}),
      N('die Industrie', 'industriell', 'industri|ell', 'ell', 'die Produktion', 'def', 'industrial', {note:'The final -e drops: industri·ell.'}),
      N('die Profession', 'professionell', 'profession|ell', 'ell', 'die Beratung', 'indef', 'professional'),
      N('die Tradition', 'traditionell', 'tradition|ell', 'ell', 'das Gericht', 'indef', 'traditional'),
      N('die Emotion', 'emotional', 'emotion|al', 'al', 'die Rede', 'indef', 'emotional', {alts:['emotionell']}),
      N('das Zentrum', 'zentral', 'zentr|al', 'al', 'die Lage', 'indef', 'central', {note:'-um drops: Zentrum → zentr·al.'}),
      N('die Aggression', 'aggressiv', 'aggress|iv', 'iv', 'der Hund', 'indef', 'aggressive', {note:'-ion goes, -iv comes.'}),
      N('die Intuition', 'intuitiv', 'intuit|iv', 'iv', 'die Bedienung', 'indef', 'intuitive', {note:'-ion goes, -iv comes.'}),
      N('der Luxus', 'luxuriös', 'luxur|iös', 'ös', 'das Hotel', 'indef', 'luxurious', {note:'Luxus → luxur·iös.'}),
      N('der Skandal', 'skandalös', 'skandal|ös', 'ös', 'das Urteil', 'indef', 'scandalous'),
      N('die Person', 'personell', 'person|ell', 'ell', 'pl Veränderungen', 'zero', 'concerning staff',
        {traps:{personal:'personal is a rare technical word: personale Identität.', 'persönlich':'persönlich means personal, private: persönliche Daten.'}})
    ]},

  { id:'art', group:'suffix', level:'B2', title:'Character and manner',
    task:'-haft, -sam, -mäßig or -gemäß? After -ung and -heit a linking -s appears.',
    els:['haft','sam','mäßig','gemäß'],
    example:N('die Regel', 'regelmäßig', 'regel|mäßig', 'mäßig', 'pl Pausen', 'zero', 'regular'),
    items:[
      N('die Tugend', 'tugendhaft', 'tugend|haft', 'haft', 'das Leben', 'indef', 'virtuous', {alts:['tugendsam']}),
      N('der Name', 'namhaft', 'nam|haft', 'haft', 'der Wissenschaftler', 'indef', 'renowned, well-known', {note:'The final -e drops: Name → nam·haft.'}),
      N('der Vorteil', 'vorteilhaft', 'vorteil|haft', 'haft', 'das Angebot', 'indef', 'advantageous'),
      N('das Rätsel', 'rätselhaft', 'rätsel|haft', 'haft', 'der Fund', 'indef', 'mysterious, puzzling'),
      N('das Märchen', 'märchenhaft', 'märchen|haft', 'haft', 'das Schloss', 'indef', 'like a fairy tale, fabulous'),
      N('der Zweifel', 'zweifelhaft', 'zweifel|haft', 'haft', 'das Vergnügen', 'indef', 'dubious, doubtful'),
      N('die Mühe', 'mühsam', 'müh|sam', 'sam', 'der Aufstieg', 'indef', 'laborious, hard-going',
        {alts:['mühevoll','mühselig'], note:'The final -e drops.', traps:{'mühelos':'mühelos means effortless, the opposite: ein müheloser Sieg.'}}),
      N('wirken', 'wirksam', 'wirk|sam', 'sam', 'das Medikament', 'indef', 'effective', {alts:['wirkungsvoll'], traps:{wirklich:'wirklich means real, actual: das wirkliche Leben.'}}),
      N('schweigen', 'schweigsam', 'schweig|sam', 'sam', 'der Mann', 'indef', 'taciturn, quiet'),
      N('die Arbeit', 'arbeitsam', 'arbeit|sam', 'sam', 'der Mensch', 'indef', 'hard-working, industrious',
        {note:'No linking -s before -sam.', traps:{arbeitslos:'arbeitslos means unemployed.', 'arbeitsfähig':'arbeitsfähig means fit for work.'}}),
      N('heilen', 'heilsam', 'heil|sam', 'sam', 'die Erfahrung', 'indef', 'salutary, doing you good', {traps:{heilbar:'heilbar means curable: eine heilbare Krankheit.'}}),
      N('der Plan', 'planmäßig', 'plan|mäßig', 'mäßig', 'die Abfahrt', 'def', 'scheduled, according to plan',
        {alts:['plangemäß'], traps:{planvoll:'planvoll means well thought out, methodical: planvolles Vorgehen.', planlos:'planlos means without a plan, aimless.'}}),
      N('die Routine', 'routinemäßig', 'routine|mäßig', 'mäßig', 'die Kontrolle', 'indef', 'routine (adj.)'),
      N('die Zeit', 'zeitgemäß', 'zeit|gemäß', 'gemäß', 'die Ausstattung', 'indef', 'up to date, in keeping with the times',
        {traps:{zeitlich:'zeitlich means concerning time: der zeitliche Ablauf.', zeitlos:'zeitlos means timeless: zeitloses Design.', zeitig:'zeitig means early: am zeitigen Morgen.'}}),
      N('die Ordnung', 'ordnungsgemäß', 'ordnung|s|gemäß', 'gemäß', 'die Kündigung', 'indef', 'proper, in due form', {alts:['ordnungsmäßig'], note:'Linking -s after -ung.', traps:{ordentlich:'ordentlich means tidy, decent: ein ordentliches Zimmer.'}}),
      N('der Vertrag', 'vertragsgemäß', 'vertrag|s|gemäß', 'gemäß', 'die Lieferung', 'indef', 'as agreed in the contract', {alts:['vertragsmäßig','vertragsgerecht'], note:'Linking -s after Vertrag.', traps:{vertraglich:'vertraglich means by contract: eine vertragliche Regelung.'}}),
      N('die Frist', 'fristgemäß', 'frist|gemäß', 'gemäß', 'die Zahlung', 'indef', 'on time, within the deadline',
        {alts:['fristgerecht'], traps:{fristlos:'fristlos means without notice: eine fristlose Kündigung.'}}),
      N('die Wahrheit', 'wahrheitsgemäß', 'wahrheit|s|gemäß', 'gemäß', 'die Aussage', 'indef', 'truthful', {alts:['wahrheitsgetreu'], note:'Linking -s after -heit.'})
    ]},

  { id:'welt', group:'suffix', level:'B2', title:'Places, fields and society',
    task:'-isch or -lich? Countries, peoples and nouns in -ik or -ie take -isch.',
    els:['isch','lich'],
    example:N('Italien', 'italienisch', 'italien|isch', 'isch', 'die Mode', 'zero', 'Italian'),
    items:[
      N('der Franzose', 'französisch', 'französ|isch', 'isch', 'die Küche', 'def', 'French', {note:'o → ö, and the final -e drops.'}),
      N('Rom', 'römisch', 'röm|isch', 'isch', 'pl Ruinen', 'zero', 'Roman', {note:'o → ö.'}),
      N('Europa', 'europäisch', 'europä|isch', 'isch', 'pl Länder', 'zero', 'European', {note:'a → ä: Europa → europä·isch.'}),
      N('der Islam', 'islamisch', 'islam|isch', 'isch', 'die Kunst', 'zero', 'Islamic'),
      N('Amerika', 'amerikanisch', 'amerika|n|isch', 'isch', 'die Literatur', 'zero', 'American', {note:'An -n- is inserted: amerika·n·isch.'}),
      N('der Brite', 'britisch', 'brit|isch', 'isch', 'der Humor', 'def', 'British', {note:'The final -e drops.'}),
      N('der Mittelstand', 'mittelständisch', 'mittelständ|isch', 'isch', 'das Unternehmen', 'indef', 'medium-sized (business)', {note:'a → ä.'}),
      N('die Stadt', 'städtisch', 'städt|isch', 'isch', 'das Schwimmbad', 'def', 'municipal, urban', {note:'a → ä.'}),
      N('das Tier', 'tierisch', 'tier|isch', 'isch', 'pl Produkte', 'zero', 'animal (adj.)'),
      N('die Kosmetik', 'kosmetisch', 'kosmet|isch', 'isch', 'die Behandlung', 'indef', 'cosmetic', {note:'-ik drops: Kosmetik → kosmet·isch.'}),
      N('die Psychologie', 'psychologisch', 'psycholog|isch', 'isch', 'das Gutachten', 'indef', 'psychological', {note:'-ie drops.', traps:{psychisch:'psychisch means mental, of the psyche: psychische Probleme.'}}),
      N('die Organisation', 'organisatorisch', 'organisat|or|isch', 'isch', 'pl Probleme', 'zero', 'organisational',
        {note:'-ion becomes -or- before -isch: organisat·or·isch.', traps:{organisch:'organisch means organic: organische Stoffe.'}}),
      N('das Mittelalter', 'mittelalterlich', 'mittelalter|lich', 'lich', 'die Burg', 'indef', 'medieval'),
      N('die Gesellschaft', 'gesellschaftlich', 'gesellschaft|lich', 'lich', 'das Ereignis', 'indef', 'social, of society', {traps:{gesellig:'gesellig means sociable: ein geselliger Abend.'}}),
      N('die Wissenschaft', 'wissenschaftlich', 'wissenschaft|lich', 'lich', 'die Studie', 'indef', 'scientific, scholarly'),
      N('das Handwerk', 'handwerklich', 'handwerk|lich', 'lich', 'das Geschick', 'zero', 'manual, of a craft'),
      N('der Körper', 'körperlich', 'körper|lich', 'lich', 'die Arbeit', 'zero', 'physical'),
      N('die Seele', 'seelisch', 'seel|isch', 'isch', 'die Belastung', 'indef', 'mental, emotional', {note:'The final -e drops.'})
    ]},

  { id:'ohne', group:'suffix', level:'B2', title:'Without: -los and what happens at the joint',
    task:'Every answer ends in -los. Decide what happens between the noun and the suffix: nothing, a linking -s, -n or -er, or an -e that drops.',
    els:['los'],
    example:N('die Arbeit', 'arbeitslos', 'arbeit|s|los', 'los', 'pl Jugendliche', 'zero', 'unemployed'),
    items:[
      N('der Schlaf', 'schlaflos', 'schlaf|los', 'los', 'die Nacht', 'indef', 'sleepless'),
      N('die Reibung', 'reibungslos', 'reibung|s|los', 'los', 'der Ablauf', 'indef', 'smooth, without a hitch', {note:'Linking -s after -ung.'}),
      N('die Ahnung', 'ahnungslos', 'ahnung|s|los', 'los', 'pl Touristen', 'zero', 'unsuspecting, clueless', {note:'Linking -s after -ung.'}),
      N('das Obdach', 'obdachlos', 'obdach|los', 'los', 'pl Menschen', 'zero', 'homeless'),
      N('die Grenze', 'grenzenlos', 'grenze|n|los', 'los', 'die Freiheit', 'zero', 'boundless', {note:'Linking -n after the -e: grenze·n·los.'}),
      N('die Pause', 'pausenlos', 'pause|n|los', 'los', 'der Lärm', 'zero', 'non-stop', {note:'Linking -n after the -e: pause·n·los.'}),
      N('der Draht', 'drahtlos', 'draht|los', 'los', 'pl Kopfhörer', 'zero', 'wireless'),
      N('die Frist', 'fristlos', 'frist|los', 'los', 'die Kündigung', 'indef', 'without notice'),
      N('das Ende', 'endlos', 'end|los', 'los', 'pl Diskussionen', 'zero', 'endless', {note:'The final -e drops: Ende → end·los.'}),
      N('die Zeit', 'zeitlos', 'zeit|los', 'los', 'das Design', 'zero', 'timeless'),
      N('die Sprache', 'sprachlos', 'sprach|los', 'los', 'das Publikum', 'indef', 'speechless', {note:'The final -e drops: Sprache → sprach·los.'}),
      N('das Kind', 'kinderlos', 'kind|er|los', 'los', 'das Paar', 'indef', 'childless', {note:'Linking -er (the plural form): kind·er·los.'})
    ]},

  /* ============================ SAME BASE, TWO ADJECTIVES ============================ */
  { id:'paare1', group:'pairs', level:'C1', title:'Same base, two adjectives (1)', cueEn:true,
    task:'The same base takes two suffixes with two meanings. Use the English meaning to pick the right one.',
    els:['haft','lich','isch','ig','al','ell'],
    example:N('die Form', 'formal', 'form|al', 'al', 'der Fehler', 'indef', 'about the form only, not the content'),
    items:[
      N('der Schmerz', 'schmerzhaft', 'schmerz|haft', 'haft', 'die Verletzung', 'indef', 'physically painful',
        {traps:{schmerzlich:'schmerzlich is pain you feel inside: ein schmerzlicher Verlust.'}}),
      N('der Schmerz', 'schmerzlich', 'schmerz|lich', 'lich', 'der Verlust', 'indef', 'emotionally painful, sad',
        {traps:{schmerzhaft:'schmerzhaft is pain in the body: eine schmerzhafte Verletzung.'}}),
      N('das Kind', 'kindisch', 'kind|isch', 'isch', 'der Streit', 'indef', 'childish, silly (said of adults)',
        {traps:{kindlich:'kindlich is neutral or positive, like a child: kindliche Neugier.'}}),
      N('das Kind', 'kindlich', 'kind|lich', 'lich', 'die Neugier', 'zero', 'childlike, natural for a child',
        {traps:{kindisch:'kindisch is critical, said of adults who behave like children: ein kindischer Streit.'}}),
      N('die Ratio', 'rational', 'ration|al', 'al', 'die Entscheidung', 'indef', 'guided by reason, not by feeling',
        {traps:{rationell:'rationell means efficient, saving time and effort: eine rationelle Arbeitsweise.'}}),
      N('die Ratio', 'rationell', 'ration|ell', 'ell', 'die Arbeitsweise', 'indef', 'efficient, saving time and effort',
        {traps:{rational:'rational means guided by reason: eine rationale Entscheidung.'}}),
      N('das Geschäft', 'geschäftlich', 'geschäft|lich', 'lich', 'der Termin', 'indef', 'to do with business',
        {traps:{'geschäftig':'geschäftig means busy, bustling: geschäftiges Treiben.'}}),
      N('das Geschäft', 'geschäftig', 'geschäft|ig', 'ig', 'das Treiben', 'zero', 'busy, bustling',
        {traps:{'geschäftlich':'geschäftlich means to do with business: ein geschäftlicher Termin.'}}),
      N('das Herz', 'herzlich', 'herz|lich', 'lich', 'die Begrüßung', 'indef', 'warm, cordial',
        {traps:{herzhaft:'herzhaft means hearty or savoury: ein herzhaftes Frühstück.'}}),
      N('das Herz', 'herzhaft', 'herz|haft', 'haft', 'das Frühstück', 'indef', 'hearty, savoury',
        {traps:{herzlich:'herzlich means warm, cordial: eine herzliche Begrüßung.'}}),
      N('der Geist', 'geistig', 'geist|ig', 'ig', 'die Arbeit', 'zero', 'of the mind, intellectual',
        {traps:{geistlich:'geistlich means religious, of the church: geistliche Musik.'}}),
      N('der Geist', 'geistlich', 'geist|lich', 'lich', 'die Musik', 'zero', 'sacred, of the church',
        {traps:{geistig:'geistig means of the mind: geistige Arbeit.'}}),
      N('das Heim', 'heimlich', 'heim|lich', 'lich', 'das Treffen', 'indef', 'secret',
        {traps:{heimisch:'heimisch means native, local: heimische Pflanzen.'}}),
      N('das Heim', 'heimisch', 'heim|isch', 'isch', 'pl Pflanzen', 'zero', 'native, local',
        {traps:{heimlich:'heimlich means secret: ein heimliches Treffen.'}}),
      N('die Kunst', 'künstlich', 'künst|lich', 'lich', 'das Licht', 'zero', 'artificial',
        {note:'u → ü.', traps:{'künstlerisch':'künstlerisch means artistic and comes from der Künstler: künstlerische Freiheit.'}}),
      N('der Künstler', 'künstlerisch', 'künstler|isch', 'isch', 'die Freiheit', 'zero', 'artistic',
        {traps:{'künstlich':'künstlich means artificial: künstliches Licht.'}})
    ]},

  { id:'paare2', group:'pairs', level:'C1', title:'Same base, two adjectives (2)', cueEn:true,
    task:'The same base takes two suffixes with two meanings. Use the English meaning to pick the right one.',
    els:['bar','lich','ig','sam','voll','wert','mäßig','gemäß'],
    example:N('die Kosten', 'kostbar', 'kost|bar', 'bar', 'der Schmuck', 'zero', 'precious, valuable'),
    items:[
      N('das Wunder', 'wunderbar', 'wunder|bar', 'bar', 'der Abend', 'indef', 'wonderful',
        {alts:['wundervoll'], traps:{wunderlich:'wunderlich means odd, eccentric: ein wunderlicher Nachbar.', wundersam:'wundersam means strange, as if by a miracle: eine wundersame Rettung.'}}),
      N('das Wunder', 'wunderlich', 'wunder|lich', 'lich', 'der Nachbar', 'indef', 'odd, eccentric',
        {traps:{wunderbar:'wunderbar means wonderful: ein wunderbarer Abend.', wundervoll:'wundervoll means wonderful: ein wundervoller Abend.', wundersam:'wundersam means strange, as if by a miracle: eine wundersame Rettung.'}}),
      N('lösen', 'lösbar', 'lös|bar', 'bar', 'die Aufgabe', 'indef', 'solvable',
        {traps:{'löslich':'löslich means it dissolves in liquid: löslicher Kaffee.'}}),
      N('lösen', 'löslich', 'lös|lich', 'lich', 'der Kaffee', 'zero', 'soluble, instant',
        {traps:{'lösbar':'lösbar means it can be solved: eine lösbare Aufgabe.'}}),
      N('die Gewalt', 'gewaltig', 'gewalt|ig', 'ig', 'der Unterschied', 'indef', 'huge, enormous',
        {traps:{gewaltsam:'gewaltsam means by force, violent: ein gewaltsamer Umsturz.'}}),
      N('die Gewalt', 'gewaltsam', 'gewalt|sam', 'sam', 'der Umsturz', 'indef', 'violent, by force',
        {traps:{gewaltig:'gewaltig means huge, enormous: ein gewaltiger Unterschied.'}}),
      N('die Farbe', 'farbig', 'farb|ig', 'ig', 'das Papier', 'zero', 'coloured',
        {note:'The final -e drops.', traps:{farblich:'farblich means as regards colour: die farbliche Gestaltung.'}}),
      N('die Farbe', 'farblich', 'farb|lich', 'lich', 'die Gestaltung', 'def', 'as regards colour',
        {note:'The final -e drops.', traps:{farbig:'farbig means coloured, having colour: farbiges Papier.'}}),
      N('der Sinn', 'sinnlich', 'sinn|lich', 'lich', 'die Wahrnehmung', 'zero', 'of the senses, sensory',
        {traps:{sinnvoll:'sinnvoll means sensible, useful: eine sinnvolle Ergänzung.', sinnig:'sinnig means apt, thoughtful and is rare: ein sinniges Geschenk.'}}),
      N('der Sinn', 'sinnvoll', 'sinn|voll', 'voll', 'die Ergänzung', 'indef', 'sensible, useful',
        {traps:{sinnlich:'sinnlich means of the senses, sensual: sinnliche Wahrnehmung.'}}),
      N('der Preis', 'preislich', 'preis|lich', 'lich', 'pl Unterschiede', 'zero', 'as regards price',
        {traps:{preiswert:'preiswert means good value, inexpensive: ein preiswertes Hotel.'}}),
      N('der Preis', 'preiswert', 'preis|wert', 'wert', 'das Hotel', 'indef', 'good value, inexpensive',
        {alts:['preisgünstig'], traps:{preislich:'preislich means as regards price: preisliche Unterschiede.', 'preismäßig':'preismäßig means as regards price, like preislich.'}}),
      N('die Sache', 'sachlich', 'sach|lich', 'lich', 'die Diskussion', 'indef', 'objective, matter-of-fact',
        {note:'The final -e drops.', traps:{'sachgemäß':'sachgemäß means done the proper way: sachgemäße Lagerung.'}}),
      N('die Sache', 'sachgemäß', 'sach|gemäß', 'gemäß', 'die Lagerung', 'zero', 'proper, done the right way',
        {alts:['sachgerecht'], note:'The final -e drops.', traps:{sachlich:'sachlich means objective, matter-of-fact: eine sachliche Diskussion.'}}),
      N('das Recht', 'rechtlich', 'recht|lich', 'lich', 'pl Schritte', 'zero', 'legal, by means of the law',
        {traps:{'rechtmäßig':'rechtmäßig means lawful, rightful: der rechtmäßige Besitzer.'}}),
      N('das Recht', 'rechtmäßig', 'recht|mäßig', 'mäßig', 'der Besitzer', 'def', 'lawful, rightful',
        {traps:{rechtlich:'rechtlich means concerning the law: rechtliche Schritte.'}})
    ]},

  /* ============================ PREFIXES AND OPPOSITES ============================ */
  { id:'gegen', group:'prefix', level:'C1', title:'Opposites with a prefix or with -los',
    task:'Write the opposite, with one of these prefixes or with the suffix -los.',
    els:['de','in','un','miss','non','los'],
    example:O('höflich', 'unhöflich', 'un|höflich', 'un', 'die Frage', 'indef', 'impolite'),
    items:[
      O('direkt', 'indirekt', 'in|direkt', 'in', 'die Rede', 'def', 'indirect'),
      O('respektvoll', 'respektlos', 'respekt|los', 'los', 'der Ton', 'indef', 'disrespectful', {base:'der Respekt', note:'-voll (with) becomes -los (without).'}),
      O('aktiviert', 'deaktiviert', 'de|aktiviert', 'de', 'das Konto', 'indef', 'deactivated',
        {traps:{inaktiviert:'inaktiviert is a technical term from biology and chemistry (made inactive). An account or a code is switched off with another prefix.'}}),
      O('interessant', 'uninteressant', 'un|interessant', 'un', 'das Thema', 'indef', 'uninteresting'),
      O('interessiert', 'desinteressiert', 'des|interessiert', 'de', 'pl Zuhörer', 'zero', 'uninterested, indifferent', {alts:['uninteressiert'], note:'One of the few des- words (through French).'}),
      O('kompetent', 'inkompetent', 'in|kompetent', 'in', 'der Berater', 'indef', 'incompetent'),
      O('verbal', 'nonverbal', 'non|verbal', 'non', 'pl Signale', 'zero', 'non-verbal'),
      O('legal', 'illegal', 'il|legal', 'in', 'der Handel', 'def', 'illegal', {note:'in- becomes il- before l.'}),
      O('rational', 'irrational', 'ir|rational', 'in', 'das Verhalten', 'zero', 'irrational', {note:'in- becomes ir- before r.'}),
      O('verständlich', 'unverständlich', 'un|verständlich', 'un', 'die Formulierung', 'indef', 'impossible to understand',
        {alts:['missverständlich'], tip:'missverständlich also fits, with another meaning: easy to misunderstand.'}),
      O('stabil', 'instabil', 'in|stabil', 'in', 'die Lage', 'indef', 'unstable', {alts:['unstabil']}),
      O('rücksichtsvoll', 'rücksichtslos', 'rücksicht|s|los', 'los', 'der Fahrer', 'indef', 'inconsiderate, reckless', {base:'die Rücksicht', note:'The linking -s stays: rücksicht·s·los.'}),
      O('typisch', 'untypisch', 'un|typisch', 'un', 'die Reaktion', 'indef', 'untypical', {alts:['atypisch']}),
      O('motiviert', 'demotiviert', 'de|motiviert', 'de', 'pl Mitarbeiter', 'zero', 'demotivated',
        {alts:['unmotiviert'], tip:'unmotiviert also exists: without motivation from the start. demotiviert: the motivation was lost.'}),
      O('gelungen', 'misslungen', 'miss|lungen', 'miss', 'der Versuch', 'indef', 'failed', {note:'miss- takes the place of ge-: gelungen ↔ misslungen.'})
    ]},

  { id:'unin', group:'prefix', level:'B2', title:'un- or in-?',
    task:'German words and all participles take un-. Latin adjectives often take in-, which becomes im-, il- or ir- before m, l and r.',
    els:['un','in'],
    example:O('freundlich', 'unfreundlich', 'un|freundlich', 'un', 'der Kellner', 'indef', 'unfriendly'),
    items:[
      O('zuverlässig', 'unzuverlässig', 'un|zuverlässig', 'un', 'der Zeuge', 'indef', 'unreliable'),
      O('angenehm', 'unangenehm', 'un|angenehm', 'un', 'die Überraschung', 'indef', 'unpleasant'),
      O('angemessen', 'unangemessen', 'un|angemessen', 'un', 'die Kleidung', 'zero', 'inappropriate'),
      O('verbindlich', 'unverbindlich', 'un|verbindlich', 'un', 'das Angebot', 'indef', 'non-binding, without obligation'),
      O('befristet', 'unbefristet', 'un|befristet', 'un', 'der Vertrag', 'indef', 'permanent, open-ended'),
      O('erfahren', 'unerfahren', 'un|erfahren', 'un', 'pl Bewerber', 'zero', 'inexperienced'),
      O('geeignet', 'ungeeignet', 'un|geeignet', 'un', 'der Zeitpunkt', 'indef', 'unsuitable'),
      O('sympathisch', 'unsympathisch', 'un|sympathisch', 'un', 'die Stimme', 'indef', 'unlikeable', {tip:'A foreign word, but an everyday one: it takes un-.'}),
      O('populär', 'unpopulär', 'un|populär', 'un', 'die Entscheidung', 'indef', 'unpopular', {tip:'A foreign word, but an everyday one: it takes un-.'}),
      O('konsequent', 'inkonsequent', 'in|konsequent', 'in', 'die Erziehung', 'indef', 'inconsistent'),
      O('formell', 'informell', 'in|formell', 'in', 'das Treffen', 'indef', 'informal'),
      O('tolerant', 'intolerant', 'in|tolerant', 'in', 'die Gesellschaft', 'indef', 'intolerant'),
      O('akzeptabel', 'inakzeptabel', 'in|akzeptabel', 'in', 'der Vorschlag', 'indef', 'unacceptable', {alts:['unakzeptabel']}),
      O('effizient', 'ineffizient', 'in|effizient', 'in', 'das Verfahren', 'indef', 'inefficient',
        {traps:{uneffizient:'~uneffizient is sometimes heard, but it is not the standard word.'}}),
      O('offiziell', 'inoffiziell', 'in|offiziell', 'in', 'das Gespräch', 'indef', 'unofficial'),
      O('diskret', 'indiskret', 'in|diskret', 'in', 'die Frage', 'indef', 'indiscreet'),
      O('mobil', 'immobil', 'im|mobil', 'in', 'der Patient', 'indef', 'immobile', {note:'in- becomes im- before m.'}),
      O('legitim', 'illegitim', 'il|legitim', 'in', 'der Anspruch', 'indef', 'illegitimate', {note:'in- becomes il- before l.'}),
      O('relevant', 'irrelevant', 'ir|relevant', 'in', 'die Information', 'indef', 'irrelevant', {note:'in- becomes ir- before r.'}),
      O('reparabel', 'irreparabel', 'ir|reparabel', 'in', 'der Schaden', 'indef', 'irreparable', {note:'in- becomes ir- before r.'})
    ]},

  { id:'demiss', group:'prefix', level:'C1', title:'Undone or gone wrong: de-, des-, miss-, non-',
    task:'de- (sometimes des-) undoes an action, miss- says it went wrong, non- appears in a few fixed terms.',
    els:['de','miss','non'],
    example:O('zentral', 'dezentral', 'de|zentral', 'de', 'die Verwaltung', 'indef', 'decentralised'),
    items:[
      O('organisiert', 'desorganisiert', 'des|organisiert', 'de', 'die Abteilung', 'indef', 'disorganised', {alts:['unorganisiert'], note:'One of the few des- words (through French).'}),
      O('infiziert', 'desinfiziert', 'des|infiziert', 'de', 'die Wunde', 'indef', 'disinfected', {note:'One of the few des- words (through French).'}),
      O('montiert', 'demontiert', 'de|montiert', 'de', 'das Regal', 'indef', 'dismantled'),
      O('kodiert', 'dekodiert', 'de|kodiert', 'de', 'die Nachricht', 'indef', 'decoded', {alts:['decodiert']}),
      O('stabilisiert', 'destabilisiert', 'de|stabilisiert', 'de', 'die Region', 'indef', 'destabilised', {note:'de- + stabilisiert: the s belongs to stabil, so this is not des-.'}),
      O('reguliert', 'dereguliert', 'de|reguliert', 'de', 'der Markt', 'indef', 'deregulated', {alts:['unreguliert']}),
      O('eskaliert', 'deeskaliert', 'de|eskaliert', 'de', 'der Konflikt', 'indef', 'de-escalated', {note:'de- also before a vowel: de·eskaliert.'}),
      O('installiert', 'deinstalliert', 'de|installiert', 'de', 'das Programm', 'indef', 'uninstalled', {note:'de- also before a vowel: de·installiert.'}),
      O('kontaminiert', 'dekontaminiert', 'de|kontaminiert', 'de', 'der Boden', 'indef', 'decontaminated'),
      O('geglückt', 'missglückt', 'miss|glückt', 'miss', 'der Start', 'indef', 'failed, gone wrong', {note:'miss- takes the place of ge-: geglückt ↔ missglückt.'}),
      O('beachtet', 'missachtet', 'miss|achtet', 'miss', 'pl Regeln', 'zero', 'disregarded', {alts:['unbeachtet'], note:'miss- takes the place of be-: beachten ↔ missachten.'}),
      O('konform', 'nonkonform', 'non|konform', 'non', 'das Verhalten', 'zero', 'non-conformist')
    ]},

  { id:'los', group:'prefix', level:'B2', title:'With or without: -voll, -reich, -haft ↔ -los',
    task:'Write the opposite with -los. Watch the linking -s, and two irregular pairs.',
    els:['los'],
    example:O('wertvoll', 'wertlos', 'wert|los', 'los', 'das Bild', 'indef', 'worthless', {base:'der Wert'}),
    items:[
      O('erfolgreich', 'erfolglos', 'erfolg|los', 'los', 'die Suche', 'indef', 'unsuccessful', {base:'der Erfolg'}),
      O('sinnvoll', 'sinnlos', 'sinn|los', 'los', 'die Regel', 'indef', 'pointless', {base:'der Sinn'}),
      O('hoffnungsvoll', 'hoffnungslos', 'hoffnung|s|los', 'los', 'der Blick', 'indef', 'hopeless', {base:'die Hoffnung', note:'The linking -s stays.'}),
      O('humorvoll', 'humorlos', 'humor|los', 'los', 'der Lehrer', 'indef', 'humourless', {base:'der Humor'}),
      O('verantwortungsvoll', 'verantwortungslos', 'verantwortung|s|los', 'los', 'das Handeln', 'zero', 'irresponsible', {base:'die Verantwortung', note:'The linking -s stays.'}),
      O('geschmackvoll', 'geschmacklos', 'geschmack|los', 'los', 'die Einrichtung', 'indef', 'tasteless', {base:'der Geschmack'}),
      O('taktvoll', 'taktlos', 'takt|los', 'los', 'die Bemerkung', 'indef', 'tactless', {base:'der Takt'}),
      O('liebevoll', 'lieblos', 'lieb|los', 'los', 'die Dekoration', 'indef', 'loveless, done without care', {base:'die Liebe', note:'Irregular: the -e- of liebevoll goes: lieb·los.'}),
      O('mühevoll', 'mühelos', 'mühe|los', 'los', 'der Sieg', 'indef', 'effortless', {base:'die Mühe'}),
      O('sorgenvoll', 'sorglos', 'sorg|los', 'los', 'das Leben', 'indef', 'carefree', {base:'die Sorge', alts:['sorgenlos','sorgenfrei'], note:'Irregular: sorgenvoll ↔ sorglos.'}),
      O('schmerzhaft', 'schmerzlos', 'schmerz|los', 'los', 'die Behandlung', 'indef', 'painless', {base:'der Schmerz', alts:['schmerzfrei']}),
      O('fehlerhaft', 'fehlerlos', 'fehler|los', 'los', 'die Übersetzung', 'indef', 'flawless', {base:'der Fehler', alts:['fehlerfrei']})
    ]},

  /* ============================ BONUS ============================ */
  { id:'stark', group:'bonus', level:'B2', title:'Bonus: stronger with a noun in front',
    task:'Make the adjective stronger with a word from the box. These pairs are fixed.',
    els:['intens'],
    bank:['Bettel','Bild','Blitz','Butter','Eis','Feder','Gift','Glas','hoch','Kern','Knall','Nagel','Spott','Stein','Stock','Tod'],
    example:N('sehr weiß', 'schneeweiß', 'schnee|weiß', 'intens', 'pl Zähne', 'zero', 'snow-white'),
    items:[
      N('sehr reich', 'steinreich', 'stein|reich', 'intens', 'pl Erben', 'zero', 'filthy rich'),
      N('sehr leicht', 'federleicht', 'feder|leicht', 'intens', 'der Rucksack', 'indef', 'light as a feather'),
      N('sehr schön', 'bildschön', 'bild|schön', 'intens', 'die Landschaft', 'indef', 'pretty as a picture', {alts:['wunderschön','bildhübsch']}),
      N('sehr weich', 'butterweich', 'butter|weich', 'intens', 'die Birne', 'indef', 'soft as butter'),
      N('leuchtend grün', 'giftgrün', 'gift|grün', 'intens', 'der Pullover', 'indef', 'lurid green', {alts:['grasgrün']}),
      N('leuchtend rot', 'knallrot', 'knall|rot', 'intens', 'das Auto', 'indef', 'bright red', {alts:['feuerrot']}),
      N('sehr schnell', 'blitzschnell', 'blitz|schnell', 'intens', 'die Reaktion', 'indef', 'lightning-fast', {alts:['pfeilschnell']}),
      N('sehr arm', 'bettelarm', 'bettel|arm', 'intens', 'die Familie', 'indef', 'desperately poor'),
      N('sehr aktuell', 'hochaktuell', 'hoch|aktuell', 'intens', 'das Thema', 'indef', 'highly topical', {alts:['brandaktuell']}),
      N('sehr kalt', 'eiskalt', 'eis|kalt', 'intens', 'das Getränk', 'indef', 'ice-cold', {alts:['eisgekühlt']}),
      N('sehr müde', 'todmüde', 'tod|müde', 'intens', 'pl Wanderer', 'zero', 'dead tired', {alts:['hundemüde']}),
      N('ganz neu', 'nagelneu', 'nagel|neu', 'intens', 'das Fahrrad', 'indef', 'brand new', {alts:['brandneu']}),
      N('völlig gesund', 'kerngesund', 'kern|gesund', 'intens', 'das Baby', 'indef', 'perfectly healthy'),
      N('sehr billig', 'spottbillig', 'spott|billig', 'intens', 'der Flug', 'indef', 'dirt cheap'),
      N('sehr dunkel', 'stockdunkel', 'stock|dunkel', 'intens', 'die Nacht', 'indef', 'pitch-dark', {alts:['stockfinster'], tip:'Before an ending the e of dunkel drops: eine stockdunkle Nacht.'}),
      N('sehr klar', 'glasklar', 'glas|klar', 'intens', 'das Wasser', 'zero', 'crystal clear', {alts:['kristallklar']})
    ]}
  ];
})();
